name: Daily Integration Tests

on:
  schedule:
    - cron: '0 15 * * *' # Runs at 8:00 AM PST daily
  workflow_dispatch:  # Enable manual runs

jobs:
  daily_integration_run_prod:
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
  
  # Need to rewrite the job here because there is no straightforward way to pass secrests to reusable workflows
  daily_integration_run_devel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SPANNER_CASSANDRA_ADAPTER_CICD_SERVICE_ACCOUNT }}'
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: integration
        INTEGRATION_TEST_INSTANCE: ${{secrets.INTEGRATION_TEST_INSTANCE}}
        SPANNER_ENDPOINT: ${{secrets.SPANNER_DEVEL_ENDPOINT}}
    
  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [daily_integration_run_prod, daily_integration_run_devel]
    if: failure()
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if ('${{ needs.daily_integration_run_prod.result }}' === 'failure') {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'ðŸš¨ [PROD] Daily integration tests against prod failed!',
                body: `See [failed job](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              });
            }
            if ('${{ needs.daily_integration_run_devel.result }}' === 'failure') {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'ðŸš¨ [DEVEL] Daily integration tests against devel failed!',
                body: `See [failed job](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              });
            }
